# python train_hivt_unimodal_model_120m_goal_ver8_v4_centerline.py
python train_hivt_unimodal_model_120m_goal_ver8_v4_centerline_v2.py
python train_hivt_unimodal_model_120m_goal_ver8_v4_centerline_v3.py
