l1_objective_av_ref:
  _target_: tuplan_garage.planning.training.modeling.objectives.l1_objective_for_multimodal_av_ref.L1ObjectiveAV
  _convert_: 'all'
  weight: 1.0  # weight contribution to the overall loss
