l1_objective_av:
  _target_: tuplan_garage.planning.training.modeling.objectives.l1_objective_for_unimodal_headingLoss_av.L1ObjectiveAV
  _convert_: 'all'
  weight: 1.0  # weight contribution to the overall loss
